# Generated by Django 3.1.7 on 2021-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_video_link',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(blank=True, to='music.Category'),
        ),
    ]
