# Generated by Django 3.1.7 on 2021-07-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210707_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='sort_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
