# Generated by Django 3.1.7 on 2021-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_sort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
