# Generated by Django 3.1.7 on 2021-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_category_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-primary', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
